### ISSUE TITLE
Add an error message for unsupported browsers

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/formrenderer-base#103]
This is what we show in IE8 when JavaScript is on:

![screen shot 2015-09-07 at 3 29 52 pm](https://cloud.githubusercontent.com/assets/1328849/9723398/4ca16172-5575-11e5-99d1-731b2776487c.png)

We need to tell the user to upgrade their browser instead.

**Comment by ajb** [comment]
Hmm yeah, I'm not sure why the browser-update alert isn't popping up.

**Comment by jrubenoff** [comment]
Even if `browser-update` appears, the message is still inaccurate.

**Comment by ajb** [comment]
Actually, I'm only seeing this issue when using Compatibility Mode. Otherwise, the form renders (albeit with terrible styles) and the browser-update is displayed.
