### ISSUE TITLE
Radio field not selected

### ISSUE THREAD

**Issue by obaid** [dobtco/formrenderer-base#105]
Ok, so I am trying to test this out and I am having issue with radio button not being selected when the form is re-loaded. Is there a specific way the radio field is stored on the server side?

**Comment by ajb** [comment]
Hey there,

This might help: https://github.com/dobtco/formrenderer-base/blob/eda83e794cb3e97bd1c55edf421437df4799572c/test/fixtures/internal.js#L44-L50
