### ISSUE TITLE
Allow specific tags in field descriptions

### ISSUE THREAD

**Issue by vlymar** [dobtco/formrenderer-base#159]
Previously we allowed a whitelisted set of html tags to appear in field descriptions. After we discovered an XSS vulnerability with the sanitization of this field, we hotfixed it by removing all tag support.

Restore support for a small subset of tags.

Tentative list:
```
a

p
br

# from josh's comment
b
strong
em
i
```

We previously supported `img`, I plan to not re-instate support for it because it can also be used to trigger javascript (`onerror`)

cc @kariannemah 

Reference: 
https://github.com/dobtco/screendoor-v2/issues/4771

**Comment by jrubenoff** [comment]
From what Kari's shown me, it seems like a lot of current customer issues are coming from emphasis tags (`b`, `strong`, `em`, `i`).

**Comment by kariannemah** [comment]
+1 on what Josh's said but `<br>` and `<p>` figure prominently, too.

I'm fine with not re-instating support for `<img>`.

**Comment by vlymar** [comment]
closed with https://github.com/dobtco/formrenderer-base/pull/160
