### ISSUE TITLE
Get usage stats for versions by site

### ISSUE THREAD

**Issue by vlymar** [dobtco/formrenderer-base#162]
**This issue was moved to dobtco/dobt#2330**

**Comment by vlymar** [comment]
Unfortunately cloudfront doesn't expose the exact information we need to do this by default.

It shows you top referrers and top objects separately, but not top referrers by object. The referrer lets us determine the user (its the site that made the request), and the object is the version they requested.

I've enabled logging for our formrenderer-base cloudfront distribution. This logs every single request for the formrenderer assets, including referrer and object, and dumps them in s3 roughly every hour. We should start getting these in the next 4 hours.

I'll analyze the log files in a few hours to make sure we're getting the info we need. Hopefully we can start identifying requests to old versions right away, at least for the frequently requested ones. We'll probably need to accumulate several days of logs for an in depth analysis though.

**Comment by vlymar** [comment]
Turns out we can actually almost exactly what we need by searching `[FormRenderer API]` in papertrail. This reports the url of the form and the formrenderer version.

This doesn't tell us if the embed is requesting `0` or `0.19.0` (because the `0` object in cloudfront probably returns version `0.19.0`, but it at least gets us close. We can then cross reference the cloudfront logs against the papertrail logs.

Papertrail stores 2 weeks worth of logs.

**Comment by vlymar** [comment]
[Here's](https://docs.google.com/spreadsheets/d/1rvcHSbPloAo4uFLIt1RYXZthhfGwCL3BbkyA1Jt09fY/edit#gid=1293471826) a spreadsheet of sites that made API requests using formrenderer in the last two weeks.

Notes:
- this filters out all requests from a `forms.fm` site. forms.fm always includes latest formrenderer
- Many/most of the requests for higher versions are likely pinned to `1`
  - 1.2.4 was released 10/30, so requests for versions 1.2.4 and above are likely to come from requests to the autoupdating `1` version.

It'l be easier to get conclusive information on who is pinning what when I have a few days of cloudfront logs to analyze but this is enough to get started.

**Comment by vlymar** [comment]
@kariannemah, let me know if there is some alternate format that would be easier for you to use. Also, if you need to see the specific url (so you can figure out which project is on what version), I can get you that info too. I omitted it from the aggregation because otherwise the list gets huge.

**Comment by kariannemah** [comment]
Thanks for pulling this together. Why are some requests "unknown"?

**Comment by vlymar** [comment]
I haven't dug into that yet.

We log the requests as unknown if the `X-FR-Version` or `X-FR-URL` request headers are not present.

Could be that the formrenderer clients are so old they don't send that data.

We started sending those headers in `0.6.0`, around 3 years ago. I should be able to track down those requests once I can go over the cloudfront logs.

**Comment by vlymar** [comment]
I just investigated one request that returns "unknown" versions - 

its for this form - https://www.propublica.org/getinvolved/have-you-been-harmed-in-a-medical-facility-share-your-story

They're pulling 0.3.10!

**Comment by vlymar** [comment]
putting this on hold for a few days, will analyze cloudfront logs then

**Comment by kariannemah** [comment]
Leaving aside the unknown requests for now, the good news is that there aren't that many customers pinned to `1.0.0` or below to reach out to:

- Thought Catalog
- State Department
- ProPublica. wnyc.org, AL.com, pilotonline.com, and hamptonroads.com are embedding ProPublica's forms as part of a reporting partnership. I think it will be suffice to just email Terry.
- TechCongress
- IMCO / #3de3: Both tresdetres.mx and 3de3.mx are theirs.
- Arizona Republic (azcentral.com)
- Texas Tribune 
- GovLab
- DataSF (City and County of San Francisco)
- Chattahoochee Hills Charter School (Clay's school)

Inactive forms:
- LA Times (graphics.latimes.com): The project's now unlisted.
- Everytown: Users haven't logged on in over a year.
- Global Innovation Exchange: The project is unlisted and the account churned a while ago.

Victor, can you grab the specific URLs for...
- http://static.azcentral.com/
- https://www.texastribune.org/ (I think the request for `0.19.0` is for an old ProPublica partnership form.)
- https://media.wnyc.org/
- http://desafios.sanpedro.gob.mx (My guess is this is related to #3de3.)
- http://govlabacademy.org/

**Comment by vlymar** [comment]
This issue was moved to dobtco/dobt#2330

**Comment by vlymar** [comment]
### Specific URLs

http://static.azcentral.com/
```
url=http://static.azcentral.com/child-safety-form/ version=1.1.4
url=http://static.azcentral.com/child-safety-form/ version=1.2.7
url=http://static.azcentral.com/election-survey/ version=0.19.0
url=http://static.azcentral.com/school-bus-safety/ version=0.19.0
url=http://static.azcentral.com/teacher-shortage-arizona/ version=1.1.4
url=http://static.azcentral.com/teacher-shortage-arizona/ version=1.2.7
```

https://www.texastribune.org/

https://media.wnyc.org/

http://desafios.sanpedro.gob.mx

http://govlabacademy.org/
