### ISSUE TITLE
how to render form that created using formbuilder instead of screendoor ?

### ISSUE THREAD

**Issue by nishantvichhi** [dobtco/formrenderer-base#28]
as you have mention in document that Rendering forms without Screendoor. can you provide example how to render form that created from formbuilder ?

**Comment by mgaribay** [comment]
@nishantvichhi try this in the page you want render the form

 <form data-formrenderer></form>
<script>
        new FormRenderer({
            project_id: 1,
            response_fields:<?= $formDataInJson; ?>,
            response: {
                id: 'xxx',
                responses: {}
            }
        });
    </script>

**Comment by mgaribay** [comment]
@nishantvichhi try this
```
<form data-formrenderer></form>
<script>
        new FormRenderer({
            project_id: 1,
            response_fields:<?= $formDataInJson; ?>,
            response: {
                id: 'xxx',
                responses: {}
            }
        });
    </script>
```

And make sure you remove the first 10 chars and the last one from the generated formbuilder json
```
{"fields": ............  }
```
