### ISSUE TITLE
Use standard header elements (h1, h2, h3...) for block of text and section break?

### ISSUE THREAD

**Issue by ajb** [dobtco/formrenderer-base#42]
h/t @sinker

**Comment by ajb** [comment]
@jrubenoff any thoughts?

**Comment by jrubenoff** [comment]
This would be great for section headers. Maybe `h2` / `h3` / `h4` instead? If you're embedding the form, you might want flexibility to put the form's name as an `h1` at the top of the page.

Not sure we can assume that blocks of text will always be headings, though.

**Comment by ajb** [comment]
Sounds right. I'll plan on replacing `fr_section_name` with an appropriately-sized header, and removing the wrapping `<p>` from `section_break.eco` to achieve parity with `block_of_text.eco`. (Semi-unrelated)
