### ISSUE TITLE
Character counter pluralization

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/formrenderer-base#80]
This should be "1 character" / "1 word".

![screen shot 2015-05-21 at 1 39 03 pm](https://cloud.githubusercontent.com/assets/1328849/7758470/c7ff322a-ffbe-11e4-82ee-0b0eba28c77b.png)

**Comment by ajb** [comment]
can you check against master? the units are not displayed in the latest
version.

On Thursday, May 21, 2015, Josh Rubenoff <notifications@github.com> wrote:

> This should be "1 character" / "1 word".
>
> [image: screen shot 2015-05-21 at 1 39 03 pm]
> <https://cloud.githubusercontent.com/assets/1328849/7758470/c7ff322a-ffbe-11e4-82ee-0b0eba28c77b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/issues/80>.
>


-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker
