### ISSUE TITLE
Allow basic HTML (<a>, <em>, <strong>) inside of checkbox options?

### ISSUE THREAD

**Issue by ajb** [dobtco/formrenderer-base#82]
cf https://app.frontapp.com/api/1/noauth/open_in_front/L2luYm94ZXMvc2hhcmVkL3VuaWZpZWQvb3Blbi8yMjQzOTAwMz9tZXNzYWdlPTMyNTI3MTMx

Seems like a potentially bad idea, though. @jrubenoff: thoughts?

**Comment by jrubenoff** [comment]
Nope. That seems inaccessible... you want to be able to click on the entire label to activate the checkbox.

I like Kari's solution:

![screen shot 2015-05-26 at 10 46 28 am](https://cloud.githubusercontent.com/assets/1328849/7819116/80271920-0394-11e5-8db9-6b966aac97e8.png)

**Comment by ajb** [comment]
Cool, just wanted to make sure that we didn't need to override the default browser behavior or anything. Hey, we've done it before ;)
