### ISSUE TITLE
Reword min / max lengths to be inclusive

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/formrenderer-base#84]
Not sure which repo to change this in, but...

![screen shot 2015-06-01 at 10 16 20 am](https://cloud.githubusercontent.com/assets/1328849/7918585/445ed722-0847-11e5-8809-e21703583d0c.png)

This isn't accurate, since min / max lengths are inclusive.

Maybe we can reword as:

- "Enter a number greater than [minLength-1]."
- "Enter a number less than [maxLength +1]."

- "Enter at least [minLength] words."
- "Enter up to [maxLength" words."

**Comment by ajb** [comment]
I like "up to" and "at least".

On Mon, Jun 1, 2015 at 1:21 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Not sure which repo to change this in, but...
>
> [image: screen shot 2015-06-01 at 10 16 20 am]
> <https://cloud.githubusercontent.com/assets/1328849/7918585/445ed722-0847-11e5-8809-e21703583d0c.png>
>
> This isn't accurate, since min / max lengths are inclusive.
>
> Maybe we can reword as:
>
>    - "Enter a number greater than [minLength-1]."
>    -
>
>    "Enter a number less than [maxLength +1]."
>    -
>
>    "Enter at least [minLength] words."
>    - "Enter up to [maxLength" words."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/issues/84>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by jrubenoff** [comment]
It's awkward for numbers, so I was suggesting we use both depending on the field type.

**Comment by ajb** [comment]
Ah, ok. Well numbers aren't always going to be integers, so we can't quite
do the above.

On Mon, Jun 1, 2015 at 1:54 PM, Josh Rubenoff <notifications@github.com>
wrote:

> It's awkward for numbers, so I was suggesting we use both depending on the
> field type.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/issues/84#issuecomment-107653777>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
Any other ideas for numeric inclusivity?

**Comment by jrubenoff** [comment]
Non-integer numbers seem like an edge case, so we could have a third wording here:

"Enter a number that is equal than or greater to 4.5" / "Enter a number that is less than or equal to 4.5"

This gives us friendly language for most cases and brevity for the non-integer numbers.

**Comment by ajb** [comment]
All of those solutions add additional layers of complexity, which is :-1: in my book.

I'm actually gonna do a 180º and say that I don't think this is actually a problem. "Between 1 and 10" doesn't mean that it's either inclusive or exclusive (cf http://english.stackexchange.com/a/7872), and if someone really cares, they can try their answer and find out for themselves.

**Comment by jrubenoff** [comment]
That link discusses a range between two numbers. This is for when we only have a single number limit. "Less than 1" is just a false statement.

> additional layers of complexity

I'm not super passionate about this specific issue, but attention to detail is important.

Actually, "at least" / "up to" sounds good if you put it in a complete sentence. What about:

- Enter at least [minLength] words.
- Enter up to [maxLength] words
- Enter a number that is at least [minLength].
- Enter a number up to [maxLength].

**Comment by ajb** [comment]
> This is for when we only have a single number limit. 

Whoops, yep, that renders my argument invalid.

"At least" and "up to" sound good. I assume we'll keep things the same for the "between" case?

**Comment by jrubenoff** [comment]
Yup
