### ISSUE TITLE
Accessibility check

### ISSUE THREAD

**Issue by ajb** [dobtco/formrenderer-base#96]
- ~~`aria-required` for required fields~~ already have an `<abbr title='required'>`
- ~~`[role=alertdialog]` for validation alert~~ this is a wacky spec
- Test using screenreader

**Comment by jrubenoff** [comment]
- Add fieldset / legend pattern where applicable
- Ensure all fieldset inputs have labels
- Ensure all labels have IDS or `for` attrs
